<?php
/*
Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.

Licensed under the MIT (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      https://github.com/aspose-omr-cloud/aspose-omr-cloud-php/blob/master/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.



    Aspose.OMR for Cloud API Reference

    Aspose.OMR for Cloud helps performing optical mark recognition in the cloud

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
*/

/**
 * RecognitionStatistics
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\Omr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\Omr\Model;

use \ArrayAccess;

/**
 * RecognitionStatistics Class Doc Comment
 *
 * @category    Class
 * @description OMRResponseDetails
 * @package     Aspose\Omr
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecognitionStatistics implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RecognitionStatistics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'taskMessages' => 'string[]',
        'taskResult' => 'string',
        'runSeconds' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
        'taskMessages' => null,
        'taskResult' => null,
        'runSeconds' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'taskMessages' => 'TaskMessages',
        'taskResult' => 'TaskResult',
        'runSeconds' => 'RunSeconds'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'taskMessages' => 'setTaskMessages',
        'taskResult' => 'setTaskResult',
        'runSeconds' => 'setRunSeconds'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'taskMessages' => 'getTaskMessages',
        'taskResult' => 'getTaskResult',
        'runSeconds' => 'getRunSeconds'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['taskMessages'] = isset($data['taskMessages']) ? $data['taskMessages'] : null;
        $this->container['taskResult'] = isset($data['taskResult']) ? $data['taskResult'] : null;
        $this->container['runSeconds'] = isset($data['runSeconds']) ? $data['runSeconds'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['runSeconds'] === null) {
            $invalid_properties[] = "'runSeconds' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['runSeconds'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Gets or sets Name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets taskMessages
     * @return string[]
     */
    public function getTaskMessages()
    {
        return $this->container['taskMessages'];
    }

    /**
     * Sets taskMessages
     * @param string[] $taskMessages Warnings and other messages regarding task, etc.
     * @return $this
     */
    public function setTaskMessages($taskMessages)
    {
        $this->container['taskMessages'] = $taskMessages;

        return $this;
    }

    /**
     * Gets taskResult
     * @return string
     */
    public function getTaskResult()
    {
        return $this->container['taskResult'];
    }

    /**
     * Sets taskResult
     * @param string $taskResult Indicates if each particular task passed or failed,
     * @return $this
     */
    public function setTaskResult($taskResult)
    {
        $this->container['taskResult'] = $taskResult;

        return $this;
    }

    /**
     * Gets runSeconds
     * @return double
     */
    public function getRunSeconds()
    {
        return $this->container['runSeconds'];
    }

    /**
     * Sets runSeconds
     * @param double $runSeconds Gets or sets RunSeconds
     * @return $this
     */
    public function setRunSeconds($runSeconds)
    {
        $this->container['runSeconds'] = $runSeconds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Aspose\Omr\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Aspose\Omr\ObjectSerializer::sanitizeForSerialization($this));
    }
}


